title = "Nickwasused"
author = "Nickwasused"
theme = "contrast-hugo"
baseURL = "https://nickwasused.com/"

[params]
  minimal = false
  excerpts = false
  description = "my page"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]